build:
    commands:
        - composer install --no-dev --optimize-autoloader
        - php artisan key:generate
        - php artisan migrate --force
        - php artisan config:cache
        - php artisan route:cache
        - php artisan view:cache

publish:
    directory: public

static_dirs:
    - storage
    - bootstrap/cache

php_version: '8.3.7'
